export const START_SET_COMMON_CONFIG = 'config/START_SET_COMMON_CONFIG';
export const END_SET_COMMON_CONFIG = 'config/END_SET_COMMON_CONFIG';
export const UPDATE_START_METADATA = 'config/UPDATA_START_METADATA';
export const UPDATE_SUCCESS_METADATA = 'config/UPDATE_SUCCESS_METADATA';
